/**
 * Unit tests for lib/headless-fallback-provider.cjs — HeadlessFallbackProvider.
 *
 * All tests use an injected _httpPost function to avoid real network calls (NFR-002).
 * All writes use injected _paths for filesystem isolation (os.mkdtemp).
 *
 * Covers:
 *   TC-008: injected _httpPost returns valid task JSON array → tasks written via importTasks,
 *           all status 'pending', no error; execute() returns { imported: N }.
 *   TC-009 (light): null fallbackConfig → throws before any transport is invoked.
 *   authorization header: _httpPost receives Authorization: Bearer <apiKey> in headers.
 *   missing fallbackConfig fields: each of endpoint/model/apiKey missing → throws.
 *   non-2xx response (status 401/500) → throws ERR_AI_FALLBACK_FAILED.
 *   invalid JSON in choices content → throws ERR_AI_FALLBACK_FAILED.
 *   response has no tasks → throws ERR_AI_FALLBACK_FAILED.
 *   response with tasks at data.tasks (flat object) → imported correctly.
 *   response with tasks at data.choices[0].message.content JSON → imported correctly.
 *   no real network calls: injected _httpPost is the only transport.
 *
 * Run: node test/headless-fallback-provider.test.cjs
 */
'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');

// ---------------------------------------------------------------------------
// Module import — RED phase: module does not exist yet → will fail here
// ---------------------------------------------------------------------------

let provider;
test('headless-fallback-provider module imports without throwing', () => {
  provider = require('../lib/headless-fallback-provider.cjs');
});

// ---------------------------------------------------------------------------
// Helper utilities
// ---------------------------------------------------------------------------

function makeTmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'hfp-test-'));
}

function makePaths(tmpDir) {
  return {
    tasksFile: path.join(tmpDir, '.taskmaster', 'tasks', 'tasks.json'),
  };
}

/** Build a minimal valid fallbackConfig object. */
function makeFallbackConfig(overrides) {
  return Object.assign(
    {
      endpoint: 'https://api.example.com/v1/chat/completions',
      model: 'gpt-4o',
      apiKey: 'sk-test-key-12345',
    },
    overrides
  );
}

/**
 * Build a schema-valid task object that importTasks will accept without error.
 * All 8 required fields are present.
 */
function makeValidTask(overrides) {
  return Object.assign(
    {
      id: '1',
      title: 'Task from LLM',
      description: 'A task generated by the LLM.',
      status: 'pending',
      priority: 'medium',
      dependencies: [],
      subtasks: [],
      updatedAt: '2026-07-26T00:00:00.000Z',
    },
    overrides
  );
}

/**
 * Build a minimal params object for execute().
 * execute(op, params, fallbackConfig, _inject)
 */
function makeParams(tag, overrides) {
  return Object.assign({ tag: tag || 'test-tag' }, overrides);
}

/**
 * Create an injected _httpPost that returns a direct task array (data is Array).
 * Returns { captured } so tests can inspect what was passed to _httpPost.
 */
function makeHttpPostInjectDirect(tasks) {
  const captured = { calls: [] };
  const _httpPost = async (url, options) => {
    captured.calls.push({ url, options });
    return { status: 200, json: tasks };
  };
  return { _httpPost, captured };
}

/**
 * Create an injected _httpPost that returns { tasks: [...] } (data.tasks).
 */
function makeHttpPostInjectDataTasks(tasks) {
  const captured = { calls: [] };
  const _httpPost = async (url, options) => {
    captured.calls.push({ url, options });
    return { status: 200, json: { tasks } };
  };
  return { _httpPost, captured };
}

/**
 * Create an injected _httpPost that returns an OpenAI-shaped response
 * where the tasks array is JSON-encoded in choices[0].message.content.
 */
function makeHttpPostInjectChoices(tasks) {
  const captured = { calls: [] };
  const _httpPost = async (url, options) => {
    captured.calls.push({ url, options });
    return {
      status: 200,
      json: {
        choices: [
          { message: { content: JSON.stringify(tasks) } },
        ],
      },
    };
  };
  return { _httpPost, captured };
}

/**
 * Create an injected _httpPost that returns a non-2xx status.
 */
function makeHttpPostInjectError(status, body) {
  const _httpPost = async () => ({ status, json: body });
  return { _httpPost };
}

// ---------------------------------------------------------------------------
// Export shape
// ---------------------------------------------------------------------------

test('headless-fallback-provider exports execute function', () => {
  assert.ok(typeof provider.execute === 'function',
    'execute must be exported as a function');
});

// ---------------------------------------------------------------------------
// TC-009 (light): null fallbackConfig → throws before any transport is invoked
// ---------------------------------------------------------------------------

test('TC-009: execute with null fallbackConfig throws before invoking _httpPost', async () => {
  let httpCalled = false;
  const _httpPost = async () => { httpCalled = true; return { status: 200, json: [] }; };

  let thrown;
  try {
    await provider.execute('parse-prd', makeParams('tag-null-cfg'), null, { _httpPost });
  } catch (e) {
    thrown = e;
  }

  assert.ok(thrown, 'execute must throw when fallbackConfig is null');
  assert.ok(!httpCalled, '_httpPost must NOT be called when fallbackConfig is null');
});

// ---------------------------------------------------------------------------
// Missing fallbackConfig field validation
// ---------------------------------------------------------------------------

test('missing endpoint in fallbackConfig → throws with descriptive message', async () => {
  const cfg = makeFallbackConfig({ endpoint: undefined });
  let thrown;
  try {
    await provider.execute('parse-prd', makeParams('tag-no-ep'), cfg, { _httpPost: async () => {} });
  } catch (e) {
    thrown = e;
  }
  assert.ok(thrown, 'must throw when endpoint is missing');
  assert.ok(
    thrown.message.toLowerCase().includes('endpoint'),
    'error message must mention "endpoint"; got: ' + thrown.message
  );
});

test('missing model in fallbackConfig → throws with descriptive message', async () => {
  const cfg = makeFallbackConfig({ model: undefined });
  let thrown;
  try {
    await provider.execute('parse-prd', makeParams('tag-no-model'), cfg, { _httpPost: async () => {} });
  } catch (e) {
    thrown = e;
  }
  assert.ok(thrown, 'must throw when model is missing');
  assert.ok(
    thrown.message.toLowerCase().includes('model'),
    'error message must mention "model"; got: ' + thrown.message
  );
});

test('missing apiKey in fallbackConfig → throws with descriptive message', async () => {
  const cfg = makeFallbackConfig({ apiKey: undefined });
  let thrown;
  try {
    await provider.execute('parse-prd', makeParams('tag-no-key'), cfg, { _httpPost: async () => {} });
  } catch (e) {
    thrown = e;
  }
  assert.ok(thrown, 'must throw when apiKey is missing');
  assert.ok(
    thrown.message.toLowerCase().includes('apikey') || thrown.message.toLowerCase().includes('api key'),
    'error message must mention "apiKey"; got: ' + thrown.message
  );
});

test('non-string endpoint in fallbackConfig → throws', async () => {
  const cfg = makeFallbackConfig({ endpoint: 42 });
  let thrown;
  try {
    await provider.execute('parse-prd', makeParams('tag-bad-ep'), cfg, { _httpPost: async () => {} });
  } catch (e) {
    thrown = e;
  }
  assert.ok(thrown, 'must throw when endpoint is not a string');
});

// ---------------------------------------------------------------------------
// TC-008: happy path — injected _httpPost → tasks written via importTasks
// ---------------------------------------------------------------------------

test('TC-008: direct array response → tasks written to tasks.json with status pending', async () => {
  const tmpDir = makeTmpDir();
  const _paths = makePaths(tmpDir);
  const tag = 'tc008-direct';

  const tasks = [
    makeValidTask({ id: '1', title: 'Task one' }),
    makeValidTask({ id: '2', title: 'Task two' }),
  ];

  const { _httpPost } = makeHttpPostInjectDirect(tasks);

  const result = await provider.execute(
    'parse-prd',
    makeParams(tag),
    makeFallbackConfig(),
    { _httpPost, _paths }
  );

  assert.ok(result && typeof result === 'object', 'execute must return an object');
  assert.equal(result.imported, 2, 'result.imported must equal number of tasks');

  // Verify tasks were actually written to tasks.json
  const stored = JSON.parse(fs.readFileSync(_paths.tasksFile, 'utf8'));
  const tagData = stored[tag];
  assert.ok(tagData, 'Tag namespace must exist in tasks.json');
  assert.ok(Array.isArray(tagData.tasks), 'tasks must be an array');
  assert.equal(tagData.tasks.length, 2, 'tasks.json must contain 2 tasks');

  // All statuses must be normalized to 'pending' (importTasks guarantee)
  for (const t of tagData.tasks) {
    assert.equal(t.status, 'pending',
      `Task ${t.id} status must be 'pending' after import (TC-008)`);
  }
});

test('TC-008: data.tasks shape response → imported correctly', async () => {
  const tmpDir = makeTmpDir();
  const _paths = makePaths(tmpDir);
  const tag = 'tc008-data-tasks';

  const tasks = [
    makeValidTask({ id: '1', title: 'Nested task one' }),
    makeValidTask({ id: '2', title: 'Nested task two' }),
    makeValidTask({ id: '3', title: 'Nested task three' }),
  ];

  const { _httpPost } = makeHttpPostInjectDataTasks(tasks);

  const result = await provider.execute(
    'parse-prd',
    makeParams(tag),
    makeFallbackConfig(),
    { _httpPost, _paths }
  );

  assert.equal(result.imported, 3, 'result.imported must equal 3 for data.tasks shape');

  const stored = JSON.parse(fs.readFileSync(_paths.tasksFile, 'utf8'));
  assert.equal(stored[tag].tasks.length, 3,
    'tasks.json must contain 3 tasks from data.tasks shape');
});

test('TC-008: choices[0].message.content JSON shape → imported correctly', async () => {
  const tmpDir = makeTmpDir();
  const _paths = makePaths(tmpDir);
  const tag = 'tc008-choices';

  const tasks = [
    makeValidTask({ id: '1', title: 'Choice task' }),
  ];

  const { _httpPost } = makeHttpPostInjectChoices(tasks);

  const result = await provider.execute(
    'parse-prd',
    makeParams(tag),
    makeFallbackConfig(),
    { _httpPost, _paths }
  );

  assert.equal(result.imported, 1, 'result.imported must be 1 for choices shape');

  const stored = JSON.parse(fs.readFileSync(_paths.tasksFile, 'utf8'));
  assert.equal(stored[tag].tasks.length, 1,
    'tasks.json must contain 1 task from choices shape');
  assert.equal(stored[tag].tasks[0].status, 'pending',
    'task status must be pending after import');
});

// ---------------------------------------------------------------------------
// Authorization header assertion
// ---------------------------------------------------------------------------

test('Authorization header contains Bearer <apiKey> (injected _httpPost receives it)', async () => {
  const tmpDir = makeTmpDir();
  const _paths = makePaths(tmpDir);
  const tag = 'tag-auth-check';
  const apiKey = 'sk-secret-key-9876';

  const tasks = [makeValidTask({ id: '1', title: 'Auth check task' })];
  const { _httpPost, captured } = makeHttpPostInjectDirect(tasks);

  await provider.execute(
    'parse-prd',
    makeParams(tag),
    makeFallbackConfig({ apiKey }),
    { _httpPost, _paths }
  );

  assert.equal(captured.calls.length, 1, '_httpPost must be called exactly once');
  const { options } = captured.calls[0];
  assert.ok(options && options.headers, '_httpPost must receive an options.headers object');

  const authHeader = options.headers['Authorization'] || options.headers['authorization'];
  assert.ok(authHeader, 'Authorization header must be present in _httpPost call');
  assert.ok(
    authHeader === `Bearer ${apiKey}`,
    `Authorization must be "Bearer ${apiKey}"; got: "${authHeader}"`
  );
});

test('POST URL matches fallbackConfig.endpoint', async () => {
  const tmpDir = makeTmpDir();
  const _paths = makePaths(tmpDir);
  const endpoint = 'https://custom.llm.api/v2/completions';
  const tasks = [makeValidTask({ id: '1', title: 'URL check task' })];
  const { _httpPost, captured } = makeHttpPostInjectDirect(tasks);

  await provider.execute(
    'parse-prd',
    makeParams('tag-url-check'),
    makeFallbackConfig({ endpoint }),
    { _httpPost, _paths }
  );

  assert.equal(captured.calls[0].url, endpoint,
    'URL passed to _httpPost must equal fallbackConfig.endpoint');
});

test('Content-Type header is application/json', async () => {
  const tmpDir = makeTmpDir();
  const _paths = makePaths(tmpDir);
  const tasks = [makeValidTask({ id: '1', title: 'Content-Type check' })];
  const { _httpPost, captured } = makeHttpPostInjectDirect(tasks);

  await provider.execute(
    'parse-prd',
    makeParams('tag-ct-check'),
    makeFallbackConfig(),
    { _httpPost, _paths }
  );

  const ct = captured.calls[0].options.headers['Content-Type'] ||
             captured.calls[0].options.headers['content-type'];
  assert.ok(ct && ct.includes('application/json'),
    'Content-Type header must be application/json');
});

// ---------------------------------------------------------------------------
// Non-2xx response → throws ERR_AI_FALLBACK_FAILED
// ---------------------------------------------------------------------------

test('non-2xx status 401 → throws ERR_AI_FALLBACK_FAILED', async () => {
  const { _httpPost } = makeHttpPostInjectError(401, { error: 'Unauthorized' });

  let thrown;
  try {
    await provider.execute(
      'parse-prd',
      makeParams('tag-401'),
      makeFallbackConfig(),
      { _httpPost }
    );
  } catch (e) {
    thrown = e;
  }

  assert.ok(thrown, 'must throw on 401 status');
  assert.equal(thrown.code, 'ERR_AI_FALLBACK_FAILED',
    'error.code must be ERR_AI_FALLBACK_FAILED for non-2xx; got: ' + thrown.code);
});

test('non-2xx status 500 → throws ERR_AI_FALLBACK_FAILED', async () => {
  const { _httpPost } = makeHttpPostInjectError(500, { error: 'Internal Server Error' });

  let thrown;
  try {
    await provider.execute(
      'parse-prd',
      makeParams('tag-500'),
      makeFallbackConfig(),
      { _httpPost }
    );
  } catch (e) {
    thrown = e;
  }

  assert.ok(thrown, 'must throw on 500 status');
  assert.equal(thrown.code, 'ERR_AI_FALLBACK_FAILED',
    'error.code must be ERR_AI_FALLBACK_FAILED for non-2xx; got: ' + thrown.code);
});

// ---------------------------------------------------------------------------
// Invalid JSON in choices content → throws ERR_AI_FALLBACK_FAILED
// ---------------------------------------------------------------------------

test('choices[0].message.content with invalid JSON → throws ERR_AI_FALLBACK_FAILED', async () => {
  const _httpPost = async () => ({
    status: 200,
    json: {
      choices: [
        { message: { content: 'this is not valid JSON {{{' } },
      ],
    },
  });

  let thrown;
  try {
    await provider.execute(
      'parse-prd',
      makeParams('tag-bad-json'),
      makeFallbackConfig(),
      { _httpPost }
    );
  } catch (e) {
    thrown = e;
  }

  assert.ok(thrown, 'must throw on invalid JSON in choices content');
  assert.equal(thrown.code, 'ERR_AI_FALLBACK_FAILED',
    'error.code must be ERR_AI_FALLBACK_FAILED for invalid JSON; got: ' + thrown.code);
});

// ---------------------------------------------------------------------------
// Response with no parseable tasks → throws ERR_AI_FALLBACK_FAILED
// ---------------------------------------------------------------------------

test('response with no tasks (empty object) → throws ERR_AI_FALLBACK_FAILED', async () => {
  const _httpPost = async () => ({
    status: 200,
    json: {},
  });

  let thrown;
  try {
    await provider.execute(
      'parse-prd',
      makeParams('tag-no-tasks'),
      makeFallbackConfig(),
      { _httpPost }
    );
  } catch (e) {
    thrown = e;
  }

  assert.ok(thrown, 'must throw when response contains no parseable tasks');
  assert.equal(thrown.code, 'ERR_AI_FALLBACK_FAILED',
    'error.code must be ERR_AI_FALLBACK_FAILED when no tasks found; got: ' + thrown.code);
});

test('response with null json → throws ERR_AI_FALLBACK_FAILED', async () => {
  const _httpPost = async () => ({
    status: 200,
    json: null,
  });

  let thrown;
  try {
    await provider.execute(
      'parse-prd',
      makeParams('tag-null-json'),
      makeFallbackConfig(),
      { _httpPost }
    );
  } catch (e) {
    thrown = e;
  }

  assert.ok(thrown, 'must throw when response json is null');
  assert.equal(thrown.code, 'ERR_AI_FALLBACK_FAILED',
    'error.code must be ERR_AI_FALLBACK_FAILED for null response; got: ' + thrown.code);
});

// ---------------------------------------------------------------------------
// No real network calls — _httpPost is the ONLY transport
// ---------------------------------------------------------------------------

test('no real network calls: execute only uses the injected _httpPost transport', async () => {
  // This test confirms that when _httpPost is injected, no real fetch() is called.
  // We verify this by using a fake _httpPost that tracks calls — if fetch() were
  // called without injection, it would fail (fetch not available in test env or
  // would require real network). The injected transport is the only path.
  const tmpDir = makeTmpDir();
  const _paths = makePaths(tmpDir);
  const tasks = [makeValidTask({ id: '1', title: 'No-network task' })];

  let httpCalled = false;
  const _httpPost = async () => {
    httpCalled = true;
    return { status: 200, json: tasks };
  };

  await provider.execute(
    'parse-prd',
    makeParams('tag-no-network'),
    makeFallbackConfig(),
    { _httpPost, _paths }
  );

  assert.ok(httpCalled, 'injected _httpPost must have been called');
  // If we reach here without an unhandled real fetch error, the injected path works.
});

// ---------------------------------------------------------------------------
// Request body contains model field from fallbackConfig
// ---------------------------------------------------------------------------

test('request body sent to _httpPost contains the model from fallbackConfig', async () => {
  const tmpDir = makeTmpDir();
  const _paths = makePaths(tmpDir);
  const model = 'claude-opus-4';
  const tasks = [makeValidTask({ id: '1', title: 'Model field test' })];
  const { _httpPost, captured } = makeHttpPostInjectDirect(tasks);

  await provider.execute(
    'parse-prd',
    makeParams('tag-model-check'),
    makeFallbackConfig({ model }),
    { _httpPost, _paths }
  );

  const body = captured.calls[0].options.body;
  assert.ok(body, 'options.body must be present');

  // body may be a string (JSON.stringify) or a parsed object
  const parsed = typeof body === 'string' ? JSON.parse(body) : body;
  assert.equal(parsed.model, model,
    'request body.model must match fallbackConfig.model');
});

// ---------------------------------------------------------------------------
// parseTasksFromResponse export (helper unit test)
// ---------------------------------------------------------------------------

test('parseTasksFromResponse exported and handles direct array', () => {
  if (typeof provider.parseTasksFromResponse !== 'function') {
    // Optional export — skip gracefully if not exported
    return;
  }
  const tasks = [makeValidTask({ id: '1', title: 'Direct array task' })];
  const result = provider.parseTasksFromResponse(tasks);
  assert.ok(Array.isArray(result), 'parseTasksFromResponse must return an array for direct array input');
  assert.equal(result.length, 1, 'must return 1 task');
});

test('parseTasksFromResponse exported and handles data.tasks shape', () => {
  if (typeof provider.parseTasksFromResponse !== 'function') {
    return;
  }
  const tasks = [makeValidTask({ id: '1', title: 'Nested tasks' })];
  const result = provider.parseTasksFromResponse({ tasks });
  assert.ok(Array.isArray(result), 'parseTasksFromResponse must handle data.tasks shape');
  assert.equal(result.length, 1, 'must return 1 task from data.tasks');
});
