#!/usr/bin/env bash
# context.sh — sourceable PROJECT_CONTEXT.yaml reader/writer.
# NOT executed directly. Source from other scripts:
#
#   . "$(dirname "$0")/context.sh"
#   context_load                    # reads .claude/docs/manual-tests/PROJECT_CONTEXT.yaml
#   echo "$CTX_STACK"               # java-spring | node | python | go | dotnet
#   context_write                   # persists CTX_* env vars back to YAML
#   context_is_fresh                # returns 0 if file exists and < 7 days old
#
# CTX_* env vars populated by context_load:
#   CTX_STACK CTX_AUTH CTX_PORT CTX_HEALTH_ENDPOINT
#   CTX_DB_HOST CTX_DB_PORT CTX_DB_NAME CTX_DB_USER
#   CTX_REDIS_HOST CTX_REDIS_PORT
#   CTX_KC_BO_REALM CTX_KC_BO_CLIENT CTX_KC_EU_REALM CTX_KC_EU_CLIENT
#   CTX_KAFKA_BROKER CTX_BO_USER

CONTEXT_FILE="${MANUAL_TEST_CONTEXT_FILE:-.claude/docs/manual-tests/PROJECT_CONTEXT.yaml}"
CONTEXT_MAX_AGE_DAYS=7

context_is_fresh() {
  local file="${1:-$CONTEXT_FILE}"
  [ -f "$file" ] || return 1
  local mtime now age
  mtime=$(stat -f %m "$file" 2>/dev/null || stat -c %Y "$file" 2>/dev/null)
  [ -z "$mtime" ] && return 1
  now=$(date +%s)
  age=$(( (now - mtime) / 86400 ))
  [ "$age" -lt "$CONTEXT_MAX_AGE_DAYS" ]
}

context_load() {
  local file="${1:-$CONTEXT_FILE}"
  [ -f "$file" ] || return 1
  # Heredoc-in-$(…) is not portable to bash 3.2 (macOS default).
  # Write the parser to a temp file, then invoke it.
  local _py
  _py=$(mktemp -t ctxload.XXXXXX) || return 1
  cat > "$_py" <<'PY'
import sys, re
with open(sys.argv[1]) as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        m = re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*):\s*(.*)$', line)
        if not m:
            continue
        key = m.group(1)
        val = m.group(2).strip().strip('"\'')
        if not val or val == 'null':
            continue
        env_key = 'CTX_' + re.sub(r'[^A-Z0-9_]', '_', key.upper())
        print(f'{env_key}={repr(val)}')
PY
  eval "$(python3 "$_py" "$file")"
  rm -f "$_py"
}

context_write() {
  local file="${1:-$CONTEXT_FILE}"
  local dir; dir="$(dirname "$file")"
  mkdir -p "$dir"
  local ts; ts=$(date -u "+%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u)
  cat > "$file" <<EOF
# Auto-generated by scripts/api.sh PRIME — re-run with PRIME --refresh to update.
# Secrets (passwords, client secrets) are excluded — read from .env at runtime.
generated_at: $ts
stack: ${CTX_STACK:-unknown}
auth: ${CTX_AUTH:-unknown}
port: ${CTX_PORT:-8080}
health_endpoint: ${CTX_HEALTH_ENDPOINT:-/actuator/health}
db_host: ${CTX_DB_HOST:-localhost}
db_port: ${CTX_DB_PORT:-5432}
db_name: ${CTX_DB_NAME:-}
db_user: ${CTX_DB_USER:-postgres}
redis_host: ${CTX_REDIS_HOST:-localhost}
redis_port: ${CTX_REDIS_PORT:-6379}
kc_bo_realm: ${CTX_KC_BO_REALM:-}
kc_bo_client: ${CTX_KC_BO_CLIENT:-}
kc_eu_realm: ${CTX_KC_EU_REALM:-}
kc_eu_client: ${CTX_KC_EU_CLIENT:-}
kafka_broker: ${CTX_KAFKA_BROKER:-localhost:9092}
bo_user: ${CTX_BO_USER:-}
EOF
  echo "[context] Wrote $file" >&2
}

context_get() {
  local key="${1:-}"
  [ -z "$key" ] && return 1
  local env_key
  env_key='CTX_'"$(echo "$key" | tr '[:lower:]' '[:upper:]' | tr -c 'A-Z0-9_' '_')"
  eval "echo \"\${${env_key}:-}\""
}

context_set() {
  local key="${1:-}" val="${2:-}"
  [ -z "$key" ] && return 1
  local env_key
  env_key='CTX_'"$(echo "$key" | tr '[:lower:]' '[:upper:]' | tr -c 'A-Z0-9_' '_')"
  eval "export ${env_key}=$(printf '%q' "$val")"
}
