#!/usr/bin/env bash
# checklist-to-verification.sh — PostToolUse(Bash) hook.
# When a `run-checklist.sh ... --tag regression` command just ran, collect its
# PASS/FAIL results and fold them into .spec-flow/VERIFICATION.md.
#
# Contract: fast, non-fatal. Always exit 0. Reads tool event JSON from stdin.

# Resolve plugin root: prefer env var, fallback to script's own directory.
PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
FLOW_TOOLS="$PLUGIN_ROOT/bin/flow-tools.cjs"
VERIF_FILE=".spec-flow/VERIFICATION.md"

# --- Read stdin (the PostToolUse event JSON) ---------------------------------
input="$(cat 2>/dev/null || true)"

# --- Extract command and output via inline node -e ---------------------------
# PostToolUse shape: { tool_name, tool_input: { command }, tool_response: { output } }
parsed="$(node -e "
try {
  var ev = JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));
  var cmd = (ev.tool_input && ev.tool_input.command) || '';
  var out = (ev.tool_response && ev.tool_response.output) || '';
  process.stdout.write(JSON.stringify({ cmd: cmd, out: out }));
} catch(e) {
  process.stdout.write(JSON.stringify({ cmd: '', out: '' }));
}
" <<< "$input" 2>/dev/null || echo '{"cmd":"","out":""}')"

cmd="$(node -e "try{process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).cmd||'')}catch(e){}" <<< "$parsed" 2>/dev/null || true)"
out="$(node -e "try{process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).out||'')}catch(e){}" <<< "$parsed" 2>/dev/null || true)"

# --- Only act when command is run-checklist.sh with --tag regression ---------
if [[ "$cmd" != *"run-checklist.sh"* ]] || [[ "$cmd" != *"--tag regression"* && "$cmd" != *"--tag=regression"* ]]; then
  exit 0
fi

# --- Write output to a temp file and call verify-collect ---------------------
tmp_file="$(mktemp /tmp/spec-flow-checklist-XXXXXX.txt)"
trap 'rm -f "$tmp_file"' EXIT

printf '%s' "$out" > "$tmp_file"

# Call verify-collect; if flow-tools is missing, skip gracefully
if [[ ! -f "$FLOW_TOOLS" ]]; then
  >&2 echo "spec-flow: checklist-to-verification: flow-tools.cjs not found at $FLOW_TOOLS — skipping"
  exit 0
fi

collect_json="$(node "$FLOW_TOOLS" verify-collect --results "$tmp_file" 2>/dev/null || true)"

if [[ -z "$collect_json" ]]; then
  >&2 echo "spec-flow: checklist-to-verification: verify-collect returned no output — skipping"
  exit 0
fi

# Parse the ok/data fields inline
ok_val="$(node -e "try{var r=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));process.stdout.write(r.ok?'1':'0')}catch(e){process.stdout.write('0')}" <<< "$collect_json" 2>/dev/null || echo 0)"

if [[ "$ok_val" != "1" ]]; then
  err_val="$(node -e "try{var r=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));process.stdout.write(r.error||'unknown')}catch(e){}" <<< "$collect_json" 2>/dev/null || true)"
  >&2 echo "spec-flow: checklist-to-verification: verify-collect failed: $err_val"
  exit 0
fi

# Extract status + passed/failed arrays + truths[]
status_val="$(node -e "try{var r=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));process.stdout.write(r.data.status||'unknown')}catch(e){process.stdout.write('unknown')}" <<< "$collect_json" 2>/dev/null || echo unknown)"
passed_count="$(node -e "try{var r=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));process.stdout.write(String((r.data.passed||[]).length))}catch(e){process.stdout.write('0')}" <<< "$collect_json" 2>/dev/null || echo 0)"
failed_count="$(node -e "try{var r=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));process.stdout.write(String((r.data.failed||[]).length))}catch(e){process.stdout.write('0')}" <<< "$collect_json" 2>/dev/null || echo 0)"
truths_md="$(node -e "
try {
  var r = JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));
  var truths = r.data.truths || [];
  var failed = r.data.failed || [];
  var lines = [];
  truths.forEach(function(t){ lines.push('- [x] ' + t); });
  failed.forEach(function(f){ lines.push('- [ ] ' + (typeof f === 'string' ? f : f.id) + (f.reason ? ' — ' + f.reason : '')); });
  process.stdout.write(lines.join('\n'));
} catch(e) { process.stdout.write(''); }
" <<< "$collect_json" 2>/dev/null || true)"

now="$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%SZ")"

# --- Merge into VERIFICATION.md (create if missing) --------------------------
mkdir -p "$(dirname "$VERIF_FILE")"

if [[ ! -f "$VERIF_FILE" ]]; then
  cat > "$VERIF_FILE" <<EOF
# VERIFICATION

> Auto-generated by spec-flow checklist-to-verification hook.

## Regression Test Results

EOF
fi

# Append a new regression run block
cat >> "$VERIF_FILE" <<EOF

---

### Regression Run — $now

**Status:** $status_val
**Passed:** $passed_count  **Failed:** $failed_count

$truths_md

EOF

>&2 echo "spec-flow: checklist-to-verification: merged $passed_count passed / $failed_count failed into $VERIF_FILE [status=$status_val]"
exit 0
